name: Ablesci Daily Sign-In

on:
  # 手动触发（便于调试）
  workflow_dispatch:
  # 定时触发 —— 注意 cron 使用 **UTC**
  schedule:
    # 08 : 30 中国标准时间 (= UTC+8 ⇒ 00 : 30 UTC)
    - cron: '30 0 * * *'
    # 如需 08 : 30 America/Chicago（夏令时 UTC-5），替换为：
    # - cron: '30 13 * * *'

jobs:
  sign-in:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign-in script
        env:
          ABLESCI_COOKIE: ${{ secrets.ABLESCI_COOKIE }}
        run: python index.py
