name: Ablesci Daily Sign-In

on:
  workflow_dispatch: # 手动触发
  schedule:
    # 每天 08:30 (Asia/Shanghai) == 00:30 UTC
    - cron: "30 0 * * *" #

jobs:
  sign-in:
    runs-on: ubuntu-latest
    env:
      ABLESCI_COOKIE: ${{ secrets.ABLESCI_COOKIE }}
      SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign-in & notify
        run: python index.py
